name: BSMapSynth-env
channels:
  - trung
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py36hf537a9a_0
  - asn1crypto=1.3.0=py36_0
  - attrs=19.3.0=py_0
  - audioread=2.1.8=py36_1
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py36_0
  - cffi=1.13.2=py36hb5b8e2f_0
  - chardet=3.0.4=py36_1003
  - cryptography=2.8=py36ha12b0ac_0
  - cycler=0.10.0=py36hfc81398_0
  - dbus=1.13.12=h90a0687_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36_0
  - expat=2.2.6=h0a44026_0
  - ffmpeg=4.2=h677a3f5_0
  - freetype=2.9.1=hb4e5f40_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.63.1=hd977a24_0
  - gmp=6.1.2=hb37e062_1
  - icu=58.2=h4b95b61_1
  - idna=2.8=py36_0
  - importlib_metadata=1.4.0=py36_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.3=py36h39e3cac_0
  - ipython=7.11.1=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.16.0=py36_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.1=py_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.2.0=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.3.4=py36_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.1=py36_0
  - kiwisolver=1.1.0=py36h0a44026_0
  - lame=3.100=h1de35cc_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libflac=1.3.1=h0a44026_1002
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libogg=1.3.2=h1de35cc_0
  - libopus=1.3=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - librosa=0.7.1=py_0
  - libsndfile=1.0.26=0
  - libsodium=1.0.16=h3efe00b_0
  - libvpx=1.7.0=h378b8a2_0
  - llvm-openmp=4.0.1=hcfea43d_1
  - llvmlite=0.31.0=py36h1341992_0
  - markupsafe=1.1.1=py36h1de35cc_0
  - matplotlib=3.1.1=py36h54f8f79_0
  - mistune=0.8.4=py36h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py36hfbe908c_0
  - mkl_fft=1.0.15=py36h5e564d8_0
  - mkl_random=1.1.0=py36ha771720_0
  - more-itertools=8.0.2=py_0
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=h0a44026_1
  - notebook=6.0.3=py36_0
  - numba=0.48.0=py36h6c726b0_0
  - numpy=1.17.4=py36h890c691_0
  - numpy-base=1.17.4=py36h6575580_0
  - openh264=1.8.0=hd9629dc_0
  - openssl=1.1.1d=h1de35cc_3
  - pandas=0.25.3=py36h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.6.0=py_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pip=20.0.2=py36_1
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - ptyprocess=0.6.0=py36_0
  - pycparser=2.19=py36_0
  - pygments=2.5.2=py_0
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py36h655552a_2
  - pyrsistent=0.15.7=py36h1de35cc_0
  - pysocks=1.7.1=py36_0
  - python=3.6.9=h359304d_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyzmq=18.1.0=py36h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.6.0=py_1
  - readline=7.0=h1de35cc_5
  - requests=2.22.0=py36_1
  - resampy=0.2.2=py_0
  - scikit-learn=0.22=py36h27c97d8_0
  - scipy=1.3.2=py36h1410ff5_0
  - send2trash=1.5.0=py36_0
  - setuptools=45.1.0=py36_0
  - sip=4.19.8=py36h0a44026_0
  - six=1.14.0=py36_0
  - sqlite=3.30.1=ha441bb4_0
  - tbb=2019.8=h04f5b5a_0
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.3=py36h1de35cc_0
  - traitlets=4.3.3=py36_0
  - urllib3=1.25.8=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - wheel=0.34.1=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - x264=1!152.20180806=h1de35cc_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.1=h0a44026_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - altgraph==0.17
    - blessings==1.7
    - ftransc==7.0.1
    - macholib==1.14
    - markovify==0.8.0
    - mutagen==1.43.0
    - pafy==0.5.5
    - plumbum==1.6.8
    - pydub==0.23.1
    - pyinstaller==3.6
    - soundfile==0.10.3.post1
    - unidecode==1.1.1
    - youtube-dl==2020.1.24
prefix: /opt/anaconda3/envs/BSMapSynth-env

